main:
  - name: 文章
    url: /posts/
    weight: 1
#  - name: 笔记
#    url: /notes/
#    weight: 2
  - name: 文档
    url: /docs/
    weight: 3
  - name: 归档
    url: /archives/
    weight: 4
  - name: 关于我
    url: '#about'
    weight: 5
